name: Demo Action
on: [push]
jobs:
  version-set:
    runs-on: ubuntu-18.04
    steps:
      - name: set up run env
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sudo apt-get update
          sudo apt-get install devscripts -y
      - name: checkout
        uses: actions/checkout@v3
      - name: set env var
        run: |
          chmod +x version
          . version
          echo "lpkgdemo_version=$lpkgdemo_version; lpkgdemo_revision=$lpkgdemo_revision"
          envsubst < mkdeb/substvars.in >> substvars
          cat substvars
          sed -i 's/export//g' version >> $GITHUB_ENV
          echo "lpkgdemo_version=$lpkgdemo_version; lpkgdemo_revision=$lpkgdemo_revision"
      - name: upgrade lpkg-demo
        uses: actions/checkout@v3
        with: 
          repository: vazmin/lpkg-demo
          token: ${{secrets.GITHUB_TOKEN}}
          path: lpkg-demo
          persist-credentials: false
          fetch-depth: 0 
      - name: update substars
        run: |
          awk -F'=' 'FNR==NR {a[$1] = $2; next} $1 in a {print $1"="$2}' lpkg-demo/debian/substvars substvars > /tmp/lpkg-demo.vars
          cp /tmp/lpkg-demo.vars lpkg-demo/debian/substvars
          cat lpkg-demo/debian/substvars
          . version
          cd lpkg-demo
          dch --distribution unstable -v ${lpkgdemo_revision} -M "upgrade to ${lpkgdemo_revision}"
          cat debian/changelog
          git add debian
      - name: Push lpkg-demo changes
        uses: vazmin/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: lpkg-demo
          repository: lpkg-demo
          

