name: FastCFS Build Action
on: [push]
jobs:
  libfastcommon-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: set up build env
        run: |
          sudo apt-get update
          sudo apt-get install build-essential debhelper -y
      - name: checkout libfastcommon
        uses: actions/checkout@v3
        with: 
          repository: happyfish100/libfastcommon
          token: ${{secrets.GITHUB_TOKEN}}
          path: modules/libfastcommon/source
      - name: build libfastcommon
        run: |
          cd modules/libfastcommon/source
          dpkg-buildpackage -b --no-sign
      - name: install libfastcommon
        run: |
          for f in modules/libfastcommon/*.deb; do sudo dpkg --force-all -i $f; done;

      - name: checkout libserverframe
        uses: actions/checkout@v3
        with: 
          repository: happyfish100/libserverframe
          token: ${{secrets.GITHUB_TOKEN}}
          path: modules/libserverframe/source
      - name: build libserverframe
        run: |
          cd modules/libserverframe/source
          dpkg-buildpackage -b --no-sign
      - name: install libserverframe
        run: |
          for f in modules/libserverframe/*.deb; do sudo dpkg --force-all -i $f; done;
      
      - name: upload libfastcommon artifact 
        uses: actions/upload-artifact@v3
        with:
          name: libfastcommon
          path: modules/libfastcommon/*.deb
      - name: upload libserverframe artifact 
        uses: actions/upload-artifact@v3
        with:
          name: libserverframe
          path: modules/libserverframe/*.deb
      
